export const getJsonLdScript =
  (data: {}) => `<script type="application/ld+json">${JSON.stringify(
    data
  )}</script>
<!-- FAQPage Code Generated by https://seotoolstore.ru/tools/faq-schema-generator/ -->`;

export const getHtmlCode = (data: { question: string; answer: string }[]) => `
<!-- START - Generated by https://seotoolstore.ru/tools/faq-schema-generator/ -->
<div itemscope itemtype="https://schema.org/FAQPage">${data
  .map(
    (item) =>
      `
    <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h2 itemprop="name">${item.question}</h2>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
            <div itemprop="text">${item.answer}</div>
        </div>
    </div>`
  )
  .join('')}
</div>
<!-- END - Generated by https://seotoolstore.ru/tools/faq-schema-generator/ -->`;
